# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/LedRun/LedRun.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun || ORIG_REF_NAME==LedRun} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_gpio_0_0/LedRun_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_gpio_0_0 || ORIG_REF_NAME==LedRun_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_microblaze_0_1/LedRun_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_microblaze_0_1 || ORIG_REF_NAME==LedRun_microblaze_0_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_microblaze_0_axi_periph_1/LedRun_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_microblaze_0_axi_periph_1 || ORIG_REF_NAME==LedRun_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_mdm_1_1/LedRun_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_mdm_1_1 || ORIG_REF_NAME==LedRun_mdm_1_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_clk_wiz_1_0/LedRun_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_clk_wiz_1_0 || ORIG_REF_NAME==LedRun_clk_wiz_1_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_rst_clk_wiz_1_100M_0/LedRun_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==LedRun_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_xlconstant_0_1/LedRun_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_xlconstant_0_1 || ORIG_REF_NAME==LedRun_xlconstant_0_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_xbar_0/LedRun_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_xbar_0 || ORIG_REF_NAME==LedRun_xbar_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_dlmb_v10_1/LedRun_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_dlmb_v10_1 || ORIG_REF_NAME==LedRun_dlmb_v10_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_ilmb_v10_1/LedRun_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_ilmb_v10_1 || ORIG_REF_NAME==LedRun_ilmb_v10_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_dlmb_bram_if_cntlr_1/LedRun_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==LedRun_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_ilmb_bram_if_cntlr_1/LedRun_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==LedRun_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_lmb_bram_1/LedRun_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_lmb_bram_1 || ORIG_REF_NAME==LedRun_lmb_bram_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_uartlite_0_0/LedRun_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_uartlite_0_0 || ORIG_REF_NAME==LedRun_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_uartlite_0_1/LedRun_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_uartlite_0_1 || ORIG_REF_NAME==LedRun_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_fifo_mm_s_0_0/LedRun_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==LedRun_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_iic_0_0/LedRun_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_iic_0_0 || ORIG_REF_NAME==LedRun_axi_iic_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_intc_0_0 || ORIG_REF_NAME==LedRun_axi_intc_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_hwicap_0_0/LedRun_axi_hwicap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_hwicap_0_0 || ORIG_REF_NAME==LedRun_axi_hwicap_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_xadc_wiz_0_0/LedRun_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_xadc_wiz_0_0 || ORIG_REF_NAME==LedRun_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_xlconcat_0_0/LedRun_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_xlconcat_0_0 || ORIG_REF_NAME==LedRun_xlconcat_0_0} -quiet] -quiet

# IP: bd/LedRun/ip/LedRun_axi_timer_0_0/LedRun_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LedRun_axi_timer_0_0 || ORIG_REF_NAME==LedRun_axi_timer_0_0} -quiet] -quiet

# XDC: bd/LedRun/LedRun_ooc.xdc
