# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/01_Xilinx_FPGA/LedRun/LedRun.cache/wt [current_project]
set_property parent.project_path D:/01_Xilinx_FPGA/LedRun/LedRun.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/01_Xilinx_FPGA/LedRun/LedRun.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/hdl/LedRun_wrapper.v
add_files D:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/LedRun.bd
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_gpio_0_0/LedRun_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_gpio_0_0/LedRun_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_gpio_0_0/LedRun_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_microblaze_0_1/LedRun_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_microblaze_0_1/LedRun_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_microblaze_0_1/LedRun_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_mdm_1_1/LedRun_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_mdm_1_1/LedRun_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_mdm_1_1/LedRun_mdm_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_clk_wiz_1_0/LedRun_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_clk_wiz_1_0/LedRun_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_clk_wiz_1_0/LedRun_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_rst_clk_wiz_1_100M_0/LedRun_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_rst_clk_wiz_1_100M_0/LedRun_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_rst_clk_wiz_1_100M_0/LedRun_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_xbar_0/LedRun_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_dlmb_v10_1/LedRun_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_dlmb_v10_1/LedRun_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_ilmb_v10_1/LedRun_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_ilmb_v10_1/LedRun_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_dlmb_bram_if_cntlr_1/LedRun_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_ilmb_bram_if_cntlr_1/LedRun_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_lmb_bram_1/LedRun_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_0/LedRun_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_0/LedRun_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_0/LedRun_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_1/LedRun_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_1/LedRun_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_uartlite_0_1/LedRun_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_fifo_mm_s_0_0/LedRun_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_iic_0_0/LedRun_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_iic_0_0/LedRun_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_hwicap_0_0/LedRun_axi_hwicap_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_hwicap_0_0/LedRun_axi_hwicap_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_hwicap_0_0/LedRun_axi_hwicap_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_xadc_wiz_0_0/LedRun_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_xadc_wiz_0_0/LedRun_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_timer_0_0/LedRun_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_timer_0_0/LedRun_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/LedRun_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/01_Xilinx_FPGA/LedRun/LedRun.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/01_Xilinx_FPGA/LedRun/LedRun.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top LedRun_wrapper -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LedRun_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LedRun_wrapper_utilization_synth.rpt -pb LedRun_wrapper_utilization_synth.pb"
