# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xci
# IP: The module: 'LedRun_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xci
# IP: The module: 'LedRun_axi_intc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/01_Xilinx_FPGA/LedRun/LedRun.srcs/sources_1/bd/LedRun/ip/LedRun_axi_intc_0_0/LedRun_axi_intc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LedRun_axi_intc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
